version: "3.9"

services:
  database:
    image: postgres
    container_name: api-solid-pg
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=apisolid
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
